sudo: required
services:
  - docker

before_install:
  - docker build -t kudriavtsevandrew/ud-docker-travis-aws -f Dockerfile.dev .

script:
  - docker run kudriavtsevandrew/ud-docker-travis-aws npm run test -- --coverage
  